# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=345, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='cropping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=350)),
                ('area', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.crop')),
            ],
        ),
        migrations.CreateModel(
            name='dateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('wateryield', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='farmAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=350)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.farm')),
            ],
        ),
        migrations.CreateModel(
            name='farmPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=350)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.farm')),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('income', models.FloatField()),
                ('doorNo', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='houseAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=350)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.house')),
            ],
        ),
        migrations.CreateModel(
            name='housePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=350)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.house')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=7)),
                ('age', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.house')),
            ],
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('sequenceNo', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.farm')),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=345, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('depth', models.FloatField()),
                ('averageWaterYield', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.farm')),
            ],
        ),
        migrations.CreateModel(
            name='wellAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=350)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.well')),
            ],
        ),
        migrations.CreateModel(
            name='wellPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=350)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.well')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.house'),
        ),
        migrations.AddField(
            model_name='datetime',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.well'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.farm'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.season'),
        ),
    ]
