# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropping',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='cropping',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='cropping',
            name='season',
        ),
        migrations.RemoveField(
            model_name='datetime',
            name='well',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='house',
        ),
        migrations.RemoveField(
            model_name='farmaudio',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='farmphoto',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='houseaudio',
            name='house',
        ),
        migrations.RemoveField(
            model_name='housephoto',
            name='house',
        ),
        migrations.RemoveField(
            model_name='member',
            name='house',
        ),
        migrations.RemoveField(
            model_name='point',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='well',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='wellaudio',
            name='well',
        ),
        migrations.RemoveField(
            model_name='wellphoto',
            name='well',
        ),
        migrations.DeleteModel(
            name='crop',
        ),
        migrations.DeleteModel(
            name='cropping',
        ),
        migrations.DeleteModel(
            name='dateTime',
        ),
        migrations.DeleteModel(
            name='farm',
        ),
        migrations.DeleteModel(
            name='farmAudio',
        ),
        migrations.DeleteModel(
            name='farmPhoto',
        ),
        migrations.DeleteModel(
            name='house',
        ),
        migrations.DeleteModel(
            name='houseAudio',
        ),
        migrations.DeleteModel(
            name='housePhoto',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='point',
        ),
        migrations.DeleteModel(
            name='season',
        ),
        migrations.DeleteModel(
            name='well',
        ),
        migrations.DeleteModel(
            name='wellAudio',
        ),
        migrations.DeleteModel(
            name='wellPhoto',
        ),
    ]
