# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170915_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housephoto',
            name='photo',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
