# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170915_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaudio',
            name='audio',
            field=models.FileField(max_length=350, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='houseaudio',
            name='audio',
            field=models.FileField(max_length=350, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='wellaudio',
            name='audio',
            field=models.FileField(max_length=350, upload_to=b''),
        ),
    ]
