# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20170915_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='farmaudio',
            name='audio',
            field=models.FileField(upload_to=b'', verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='farmphoto',
            name='photo',
            field=models.ImageField(upload_to=b'', verbose_name='static/images'),
        ),
        migrations.AlterField(
            model_name='houseaudio',
            name='audio',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='wellaudio',
            name='audio',
            field=models.FileField(upload_to=b'', verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='wellphoto',
            name='photo',
            field=models.ImageField(upload_to=b'', verbose_name='static/images/'),
        ),
    ]
