# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20170915_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaudio',
            name='audio',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='farmphoto',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='houseaudio',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='wellaudio',
            name='audio',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='wellphoto',
            name='photo',
            field=models.ImageField(upload_to=b'', verbose_name=''),
        ),
    ]
