# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20170916_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='members',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmaudio',
            name='audio',
            field=models.FileField(upload_to=b'', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='farmphoto',
            name='photo',
            field=models.ImageField(upload_to=b'', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='houseaudio',
            name='audio',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='housephoto',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wellaudio',
            name='audio',
            field=models.FileField(upload_to=b'', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='wellphoto',
            name='photo',
            field=models.ImageField(upload_to=b'', verbose_name='images'),
        ),
    ]
