# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20171005_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'', verbose_name='image')),
            ],
        ),
    ]
