# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_graphcolors'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
