# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20171121_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.crop'),
        ),
    ]
