# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20171121_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onion', models.CharField(max_length=50)),
                ('tomato', models.CharField(max_length=50)),
                ('cotton', models.CharField(max_length=50)),
                ('chilli', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='market',
        ),
    ]
